### ISSUE TITLE
Error thrown on connection Lost

### ISSUE THREAD

**Issue by maheshnayer** [crossbario/autobahn-python#1065] opened 2018-10-16 12:21 UTC
Please find below the stack trace. I have a websocket server in asyncio running behind nginx. Any help appreciated. Thank you

2018-10-16 17:47:56,882 - ERROR - Exception in callback _SelectorTransport._call_connection_lost(None)
handle: <Handle _SelectorTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 606, in _call_connection_lost
    self._protocol.connection_lost(exc)
  File "/home/ubuntu/streak_streamer/venv/lib/python3.5/site-packages/autobahn/asyncio/websocket.py", line 100, in connection_lost
    self._connectionLost(exc)
  File "/home/ubuntu/streak_streamer/venv/lib/python3.5/site-packages/autobahn/websocket/protocol.py", line 2473, in _connectionLost
    WebSocketProtocol._connectionLost(self, reason)
  File "/home/ubuntu/streak_streamer/venv/lib/python3.5/site-packages/autobahn/websocket/protocol.py", line 1096, in _connectionLost
    reason_string = _maybe_tls_reason(reason.value)
AttributeError: 'NoneType' object has no attribute 'value'

**Comment by om26er** [comment] 2018-10-16 14:19
Duplicate of https://github.com/crossbario/autobahn-python/issues/1057, already fixed by https://github.com/crossbario/autobahn-python/pull/1059

**Closed by om26er** 2018-10-16 14:19 UTC

**Comment by maheshnayer** [comment] 2018-10-16 15:40
Awesome!
Also can you explain what causes this issue please. Is it related to the ssl certificate that I'm using
Thank you

**Comment by meejah** [comment] 2018-10-16 17:33
In asyncio, connection_lost with `None` means "clean close" -- so this is just a bug in autobahn+asyncio
