### ISSUE TITLE
Connecting to crossbar router started after component regularly fails

### ISSUE THREAD

**Issue by aberres** [crossbario/autobahn-python#1030] opened 2018-08-03 14:38 UTC
**Scenario**
A running application with pretty minimal code to just have a `Component` instance connecting the router.

The router is not running. It is started some seconds after the appliction.

**Expected behavior**
Initially the app obviously fails to connect to the router, when retrying it can eventually connect once the router is up.

**Observed behavior**
In a lot of cases no `join` event is fired at all. the component just stops to reconnect.

Find below the code and the log output.

```python
import os

from autobahn.asyncio.component import Component, run


def create_component():
    authentication = None

    component = Component(
        transports=[
            {
                "type": "websocket",
                "url": os.environ.get("AUTOBAHN_ROUTER", "ws://localhost:8080/ws"),
            }
        ],
        authentication=authentication,
        realm="realm1",
    )

    return component


class Application:
    def __init__(self, component):
        self.component = component

        component.on("join", self.on_join)
        component.on("leave", self.on_leave)

    async def on_join(self, session, details):
        print("JUST JOINED")

    async def on_leave(self, session, reason):
        print("JUST LEFT")


def main():
    component = create_component()

    app = Application(component)

    run([component], log_level="debug")


if __name__ == "__main__":
    main()
```

Log output:
```
2018-08-03T16:35:22 Entering re-connect loop
2018-08-03T16:35:22 trying transport 0 using connect delay 0
2018-08-03T16:35:22 connecting once using transport type "websocket" over endpoint "tcp"
2018-08-03T16:35:22 component failed: ConnectionRefusedError: [Errno 61] Connect call failed ('127.0.0.1', 8081)
2018-08-03T16:35:22 Traceback (most recent call last):
  File "/Users/berres/venv/mpptool/lib/python3.5/site-packages/txaio/aio.py", line 498, in done
    res = f.result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/Users/berres/venv/mpptool/lib/python3.5/site-packages/txaio/aio.py", line 498, in done
    res = f.result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/Users/berres/venv/mpptool/lib/python3.5/site-packages/txaio/aio.py", line 498, in done
    res = f.result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/Users/berres/venv/mpptool/lib/python3.5/site-packages/txaio/aio.py", line 498, in done
    res = f.result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 406, in wait_for
    return fut.result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 242, in _step
    result = coro.throw(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 776, in create_connection
    raise exceptions[0]
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 763, in create_connection
    yield from self.sock_connect(sock, address)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/selector_events.py", line 451, in sock_connect
    return (yield from fut)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 381, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 310, in _wakeup
    future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/selector_events.py", line 481, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 61] Connect call failed ('127.0.0.1', 8081)

2018-08-03T16:35:22 Connection failed: ConnectionRefusedError: [Errno 61] Connect call failed ('127.0.0.1', 8081)
2018-08-03T16:35:22 Entering re-connect loop
2018-08-03T16:35:22 trying transport 0 using connect delay 2.196339784522646
2018-08-03T16:35:24 connecting once using transport type "websocket" over endpoint "tcp"
2018-08-03T16:35:24 component failed: ConnectionRefusedError: [Errno 61] Connect call failed ('127.0.0.1', 8081)
2018-08-03T16:35:24 Traceback (most recent call last):
  File "/Users/berres/venv/mpptool/lib/python3.5/site-packages/txaio/aio.py", line 498, in done
    res = f.result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/Users/berres/venv/mpptool/lib/python3.5/site-packages/txaio/aio.py", line 498, in done
    res = f.result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/Users/berres/venv/mpptool/lib/python3.5/site-packages/txaio/aio.py", line 498, in done
    res = f.result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/Users/berres/venv/mpptool/lib/python3.5/site-packages/txaio/aio.py", line 498, in done
    res = f.result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 406, in wait_for
    return fut.result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 242, in _step
    result = coro.throw(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 776, in create_connection
    raise exceptions[0]
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 763, in create_connection
    yield from self.sock_connect(sock, address)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/selector_events.py", line 451, in sock_connect
    return (yield from fut)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 381, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 310, in _wakeup
    future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/selector_events.py", line 481, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 61] Connect call failed ('127.0.0.1', 8081)

2018-08-03T16:35:24 Connection failed: ConnectionRefusedError: [Errno 61] Connect call failed ('127.0.0.1', 8081)
2018-08-03T16:35:24 Entering re-connect loop
2018-08-03T16:35:24 trying transport 0 using connect delay 3.6012217300050597
2018-08-03T16:35:28 connecting once using transport type "websocket" over endpoint "tcp"
2018-08-03T16:35:28
[('logOctets', False, 'WampWebSocketClientFactory'),
 ('logFrames', False, 'WampWebSocketClientFactory'),
 ('trackTimings', False, 'WampWebSocketClientFactory'),
 ('utf8validateIncoming', True, 'WampWebSocketClientFactory'),
 ('applyMask', True, 'WampWebSocketClientFactory'),
 ('maxFramePayloadSize', 0, 'WampWebSocketClientFactory'),
 ('maxMessagePayloadSize', 0, 'WampWebSocketClientFactory'),
 ('autoFragmentSize', 0, 'WampWebSocketClientFactory'),
 ('failByDrop', True, 'WampWebSocketClientFactory'),
 ('echoCloseCodeReason', False, 'WampWebSocketClientFactory'),
 ('openHandshakeTimeout', 5, 'WampWebSocketClientFactory'),
 ('closeHandshakeTimeout', 1, 'WampWebSocketClientFactory'),
 ('tcpNoDelay', True, 'WampWebSocketClientFactory'),
 ('autoPingInterval', 0, 'WampWebSocketClientFactory'),
 ('autoPingTimeout', 0, 'WampWebSocketClientFactory'),
 ('autoPingSize', 4, 'WampWebSocketClientFactory'),
 ('version', 18, 'WampWebSocketClientFactory'),
 ('acceptMaskedServerFrames', False, 'WampWebSocketClientFactory'),
 ('maskClientFrames', True, 'WampWebSocketClientFactory'),
 ('serverConnectionDropTimeout', 1, 'WampWebSocketClientFactory'),
 ('perMessageCompressionOffers', [], 'WampWebSocketClientFactory'),
 ('perMessageCompressionAccept',
  <function WebSocketClientFactory.resetProtocolOptions.<locals>.<lambda> at 0x105042730>,
  'WampWebSocketClientFactory')]
2018-08-03T16:35:28 connection to tcp:127.0.0.1:8081 established
2018-08-03T16:35:28 GET /ws HTTP/1.1
User-Agent: AutobahnPython/18.7.1
Host: 127.0.0.1:8081
Upgrade: WebSocket
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
Sec-WebSocket-Key: dUkqaBfl5digQ2CxS+I9Sg==
Sec-WebSocket-Protocol: wamp.2.msgpack.batched,wamp.2.msgpack,wamp.2.json.batched,wamp.2.json
Sec-WebSocket-Version: 13


2018-08-03T16:35:28 received HTTP response:

b'HTTP/1.1 101 Switching Protocols\r\nServer: Crossbar\r\nUpgrade: WebSocket\r\nConnection: Upgrade\r\nSec-WebSocket-Protocol: wamp.2.msgpack.batched\r\nSec-WebSocket-Accept: KVd2/IiZeOlNJzhHpgkCDXdi698=\r\n\r\n'


2018-08-03T16:35:28 received HTTP status line in opening handshake : HTTP/1.1 101 Switching Protocols
2018-08-03T16:35:28 received HTTP headers in opening handshake : {'upgrade': 'WebSocket', 'sec-websocket-accept': 'KVd2/IiZeOlNJzhHpgkCDXdi698=', 'connection': 'Upgrade', 'server': 'Crossbar', 'sec-websocket-protocol': 'wamp.2.msgpack.batched'}
2018-08-03T16:35:28 openHandshakeTimeoutCall.cancel
JUST JOINED
^C2018-08-03T16:35:34 Shutting down due to SIGINT
(mpptool)  ~/Devel/mpptool/backend/mppbackend/mppbackend   armin-pure-robot ●✚  python just_connect.py
2018-08-03T16:35:40 Entering re-connect loop
2018-08-03T16:35:40 trying transport 0 using connect delay 0
2018-08-03T16:35:40 connecting once using transport type "websocket" over endpoint "tcp"
2018-08-03T16:35:40 component failed: ConnectionRefusedError: [Errno 61] Connect call failed ('127.0.0.1', 8081)
2018-08-03T16:35:40 Traceback (most recent call last):
  File "/Users/berres/venv/mpptool/lib/python3.5/site-packages/txaio/aio.py", line 498, in done
    res = f.result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/Users/berres/venv/mpptool/lib/python3.5/site-packages/txaio/aio.py", line 498, in done
    res = f.result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/Users/berres/venv/mpptool/lib/python3.5/site-packages/txaio/aio.py", line 498, in done
    res = f.result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/Users/berres/venv/mpptool/lib/python3.5/site-packages/txaio/aio.py", line 498, in done
    res = f.result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 406, in wait_for
    return fut.result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 242, in _step
    result = coro.throw(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 776, in create_connection
    raise exceptions[0]
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 763, in create_connection
    yield from self.sock_connect(sock, address)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/selector_events.py", line 451, in sock_connect
    return (yield from fut)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 381, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 310, in _wakeup
    future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/selector_events.py", line 481, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 61] Connect call failed ('127.0.0.1', 8081)

2018-08-03T16:35:40 Connection failed: ConnectionRefusedError: [Errno 61] Connect call failed ('127.0.0.1', 8081)
2018-08-03T16:35:40 Entering re-connect loop
2018-08-03T16:35:40 trying transport 0 using connect delay 2.3854484902708974
2018-08-03T16:35:42 connecting once using transport type "websocket" over endpoint "tcp"
2018-08-03T16:35:42
[('logOctets', False, 'WampWebSocketClientFactory'),
 ('logFrames', False, 'WampWebSocketClientFactory'),
 ('trackTimings', False, 'WampWebSocketClientFactory'),
 ('utf8validateIncoming', True, 'WampWebSocketClientFactory'),
 ('applyMask', True, 'WampWebSocketClientFactory'),
 ('maxFramePayloadSize', 0, 'WampWebSocketClientFactory'),
 ('maxMessagePayloadSize', 0, 'WampWebSocketClientFactory'),
 ('autoFragmentSize', 0, 'WampWebSocketClientFactory'),
 ('failByDrop', True, 'WampWebSocketClientFactory'),
 ('echoCloseCodeReason', False, 'WampWebSocketClientFactory'),
 ('openHandshakeTimeout', 5, 'WampWebSocketClientFactory'),
 ('closeHandshakeTimeout', 1, 'WampWebSocketClientFactory'),
 ('tcpNoDelay', True, 'WampWebSocketClientFactory'),
 ('autoPingInterval', 0, 'WampWebSocketClientFactory'),
 ('autoPingTimeout', 0, 'WampWebSocketClientFactory'),
 ('autoPingSize', 4, 'WampWebSocketClientFactory'),
 ('version', 18, 'WampWebSocketClientFactory'),
 ('acceptMaskedServerFrames', False, 'WampWebSocketClientFactory'),
 ('maskClientFrames', True, 'WampWebSocketClientFactory'),
 ('serverConnectionDropTimeout', 1, 'WampWebSocketClientFactory'),
 ('perMessageCompressionOffers', [], 'WampWebSocketClientFactory'),
 ('perMessageCompressionAccept',
  <function WebSocketClientFactory.resetProtocolOptions.<locals>.<lambda> at 0x10502c268>,
  'WampWebSocketClientFactory')]
2018-08-03T16:35:42 connection to tcp:127.0.0.1:8081 established
2018-08-03T16:35:42 GET /ws HTTP/1.1
User-Agent: AutobahnPython/18.7.1
Host: 127.0.0.1:8081
Upgrade: WebSocket
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
Sec-WebSocket-Key: vxm5IfTTjbBjPV0oSXditg==
Sec-WebSocket-Protocol: wamp.2.msgpack.batched,wamp.2.msgpack,wamp.2.json.batched,wamp.2.json
Sec-WebSocket-Version: 13


2018-08-03T16:35:43 _connectionLost: None
2018-08-03T16:35:46 skipping opening handshake timeout: WebSocket connection is already closed
```

Config of the transport:
```
{
          "type": "universal",
          "endpoint": {
            "type": "tcp",
            "port": 8081
          },
          "rawsocket": {
            "serializers": [
              "cbor",
              "msgpack",
              "ubjson",
              "json"
            ],
            "auth": {
              "anonymous": {
                "type": "static",
                "role": "backend"
              }
            }
          },
          "websocket": {
            "ws": {
              "debug": true,
              "type": "websocket",
              "serializers": [
                "cbor",
                "msgpack",
                "ubjson",
                "json"
              ],
              "auth": {
                "anonymous": {
                  "type": "static",
                  "role": "backend"
                }
              }
            }
          }
```

**Comment by meejah** [comment] 2018-08-22 22:45
I believe this is just a dupe of #1010, so closing. If you think there's more here, please re-open!

**Closed by meejah** 2018-08-22 22:45 UTC
