### ISSUE TITLE
Updating WebSocket headers on every connection attempt

### ISSUE THREAD

**Issue by meejah** [crossbario/autobahn-python#1158] opened 2019-03-27 18:49 UTC
As brought up in `#autobahn`, currently a WebSocket connection gets its headers from the Factory (via. `self.factory.headers`). However, a Factory may make many connections and it is desirable to have a hook to change the headers for each connection (for example, when doing re-connections).

One way would be to mutate the `.headers` attribute in the Factory. This will "probably" work as there is likely only one "active" protocol instance created per-factory. However, it's not very explicit.

@exarkun suggested: "maybe something like having `WebSocketClientProtocol.onConnect` allowed to return a `ConnectionRequest` (or similar) that can specify headers?

**Comment by meejah** [comment] 2019-03-27 19:16
There are other options that get set from the factory too, so it probably makes sense to at least consider them in any "return value from `onConnect`" solution.

Perhaps what we could do is internally use "the thing that `onConnect` returns" to get all the options, and the default one can itself fall back into the `Factory` (which provides backwards-compat too). New code can either make their entirely own object (that has all the options) or something like:

```
def onConnect(...):
    options = super().onConnect(..)
    options.headers["foo"] = "bar"
    return options
```

...so our implementation would have to take care to copy any mutables that are in the factory (like `.headers`).

**Comment by oberstet** [comment] 2019-03-27 19:19
I left some pointers replying to JP on IRC - which I can't access right now .. but at least for WebSocket servers, this is already there.

**Comment by meejah** [comment] 2019-03-27 19:27
Note that for servers, `onConnect` can already return custom headers, see https://github.com/crossbario/autobahn-python/blob/master/autobahn/websocket/protocol.py#L2442

This feature would be for the client side.

**Comment by exarkun** [comment] 2019-03-27 19:59
Here's some application code that I wrote that I would like to be better:

https://github.com/exarkun/gridsync/blob/a807f9310700941fc8cc8577e82e95838f94c782/gridsync/streamedlogs.py#L83-L98

As written, the ClientService will drive reconnections always using the same API token.  I would like to be able to refresh the API token on every new connection attempt.  As meejah mentioned, I could probably do this now using prepareConnection and mutation of the factory's headers attribute:

```
def update_key(get_api_token, protocol):
    protocol.factory.headers['authorization'] = "tahoe-lafs {}".format(get_api_token())

...

client_service = ClientService(..., prepareConnection=partial(update_key, get_api_token))
```

But it has the drawbacks that meejah mentioned.  It's quite easy to see how the API example meejah gave (overriding `onConnect`) could be used to do this more nicely.

**Comment by oberstet** [comment] 2019-03-30 09:17
>  It's quite easy to see how the API example meejah gave (overriding onConnect) could be used to do this more nicely.

I don't get how that would look like, as the existing `WebSocketClientProtocol.onConnect` is fired after the original WebSocket opening handshake HTTP request comes back from the server.

Whereas, what we need is: add (per connection attempt) HTTP header provided to the initial opening request from the client.

The call sequence is like this (for a Twisted based client):

1. `autobahn.twisted.websocket.WebSocketAdapterProtocol.connectionMade`: this is called by Twisted
2. `autobahn.websocket.protocol.WebSocketClientProtocol._connectionMade`: this is called by 1. and is the generic code that runs for both Twisted and asyncio clients
3. `autobahn.websocket.protocol.WebSocketClientProtocol.startHandshake`: this is called by 2. and constructs the HTTP/GET (with upgrade) the client sends to initiate the opening handshake. It is here where HTTP headers are pulled from the factory - which "is the problem"

**Comment by oberstet** [comment] 2019-03-30 09:28
Ahh, I now remember why it was designed the way it is currently.

The HTTP headers a client sends are pulled from the factory, since the only place to inject "per connection" stuff on a Twisted based WebSocket client is: `buildProtocol`

https://github.com/crossbario/autobahn-python/blob/master/autobahn/twisted/websocket.py#L517

However, that is again a callback invoked by Twisted. This always puzzled me, as it feels quite unnatural.

Twisted enforces a design where a user comes up with a factory - but all the creation of protocol instances is completely under factory control ...

---

anyways: I am open and listening to other suggestions .. better API that allows per-connection headers for clients - but I don't currently see that.

me personally, I am treating twisted client factories as "per client" and munge the factory if needed "per connection attempt" (for that client). I don't see a way how we get out of this mess in a really clean way ..

**Comment by exarkun** [comment] 2019-03-30 11:04
> me personally, I am treating twisted client factories as "per client" and munge the factory if needed "per connection attempt" (for that client).

This might be fine most of the time but it seems incompatible with `ClientService`.  `ClientService` takes one factory and then makes N connection attempts with it and there's no way to stop it from doing so (except to not use it at all).

**Comment by exarkun** [comment] 2019-03-30 11:08
> I don't get how that would look like, as the existing WebSocketClientProtocol.onConnect is fired after the original WebSocket opening handshake HTTP request comes back from the server.

I think I learned this as part of discussion here or on #1159 .  So the discussion here shouldn't be about `WebSocketClientProtocol.onConnect`.  It should be about a new callback that is called before the handshake.  Then an application can write:

```
class MyProto(WebSocketClientProtocol):
    def theNewCallback(self):
        return SomeHandshakeParams(...)
```

This is the kind of API I was imagining when I said meejah's comment would make the desired use-case easy.

**Comment by exarkun** [comment] 2019-03-30 11:11
> Twisted enforces a design where a user comes up with a factory - but all the creation of protocol instances is completely under factory control ...

This is just because "factory" is the shape of the application code that Twisted asks for when it asks for the application's logic about how to create protocol instances.  Maybe it's not a great shape but it seems to generally make sense to me.

And thinking about this point, I realize that the focus for this issue doesn't need to be so much on the protocol.  If you prefer:

```
class MyFactory(WebSocketClientFactory):
    def getHandshakeParams(self, proto):
        return HandshakeParams(...)
```

then change the protocol implementation to call this method instead of using factory attributes directly.

This API provides just as much customizability to the application, it just puts it on the factory instead of the protocol.

**Comment by oberstet** [comment] 2019-03-30 11:41
aah, ok! so the proposal is a new client side pre-connect (in the websocket opening handshake sense) callback. sorry, I didn't get that. I agree, that makes sense and would provide a clean solution.

alright, lets see how that could look like. I would opt to stick it onto protocol rather factory, and also onto the generic code (as it is useful and we can make it work on both tx and aio easily):

```
class autobahn.websocket.protocol.WebSocketClientProtocol(autobahn.websocket.protocol.WebSocketProtocol):
    def onConnecting(self):
        return autobahn.websocket.types.ConnectingRequest(headers={'foo': 'bar'})
```

Above adds 1 new callback (`onConnecting`) and 1 new type (`ConnectingRequest`). The latter would allow a user to provide per-connection attempt headers. It would also allow per-connection attempt WebSocket extensions (eg announce different WebSocket compression capabilities per-connection attempt).

Above `onConnecting` callback would be invoked after the TCP/TLS connection is established, but right before the client start the initial WebSocket opening handshake. "connect" is an overloaded word. Here, it is about websocket rather than TCP/TLS.

---

My only question would be: should we add a parameter to `onConnecting`? At the point where the TCP or TLS connection is established, things I might be interested in the `onConnecting` callback body boil down to:

The peer (websocket server) transport details: IP address, port or negotiated TLS ciphers, server cert or even TLS capabilities on the negotiated TLS, such as TLS channel binding

> rgd the last one (channel binding): we currently have a hack to get that from a private attribute from twisted: https://github.com/crossbario/autobahn-python/blob/cfb01d7d431a60a69ad78f26281c217275959fcc/autobahn/twisted/util.py#L94 - but this is OT rgd the issue here ..

**Comment by exarkun** [comment] 2019-03-30 12:58
> The peer (websocket server) transport details: IP address, port or negotiated TLS ciphers, server cert or even TLS capabilities on the negotiated TLS, such as TLS channel binding

Twisted protocols have access to all of this information via their transport.  Does that help at all?  I'm not sure what access to a transport the Autobahn generic protocol might have.

**Comment by meejah** [comment] 2019-04-03 04:12
I would say a first cut could/should include "anything we currently get via `Factory.*` attribute access" probably (into `ConnectingRequest`)? So looking at `startHandshake` in the client protocol, that would mean the following as possibilities (for many, `None` is a useful default):

- `useragent`
- `host` (required)
- `port` (required)
- `resource` (required)
- `headers`
- `origin`
- `protocols`

As for a parameter: maybe to be extra-explicit we could include a `transport_information` parameter with "permitted" attributes/functions (i.e. as a first cut, anything that overlaps between Twisted and asyncio -- and worst-case maybe we need some "generic" abstraction to translate?) Or something? (For now, it could just pass `.transport` and then if you're "a Twisted implementation" you can use anything Twisted provides, ditto for asyncio...)

**Comment by meejah** [comment] 2019-04-03 04:28
I guess another useful source of "what could be in `ConnectingRequest`" is stuff in `WebSocketClientFactory.setSessionParameters`...

**Comment by oberstet** [comment] 2019-04-03 07:03
Not sure we are talking about the same? What I meant with my last comment above is the following.

Do we want A):

```python
class autobahn.websocket.protocol.WebSocketClientProtocol(autobahn.websocket.protocol.WebSocketProtocol):
    def onConnecting(self):
        return autobahn.websocket.types.ConnectingRequest(headers={'foo': 'bar'})
```

OR do we want B):

```python
class autobahn.websocket.protocol.WebSocketClientProtocol(autobahn.websocket.protocol.WebSocketProtocol):
    def onConnecting(self, transport_details: TransportDetails):
        return autobahn.websocket.types.ConnectingRequest(headers={'foo': 'bar'})
```

---

The `TransportDetails` is at the TCP/TLS level - even before anything HTTP, so it cannot contain eg `useragent` - this is a HTTP client requesting side attribute, and if so, it should reside on `ConnectingRequest`.

`TransportDetails` could contain:

* `host`: IP address of the server the TCP is actually connected to
* `port`: IP port of the server the TCP is actually connected to
* `cipher`: The TLS cipher negotiated
* `certificate`: The TLS server certificate

While `useragent`, `headers`, `origin`, `protocols` would be attributes on `ConnectingRequest`.

`resource`: if that is to meant as "HTTP resource", effectively the URL path component of the fully qualified WebSocket URL, yes in principle, but: a WebSocket URL can also have query components (`?foo=bar`), but cannot contains a HTTP fragment identifier (`..#foobar` is an _invalid_ WebSocket URL and Autobahn server will deny accepting that)


* `headers`:

**Comment by meejah** [comment] 2019-04-03 17:01
Sorry, I was talking about two different things: what to put in `ConnectingRequest` (besides "headers" which is the immediate need/request here) and "should we include 'transport details' or just 'the underlying transport instance or what".

All my suggestions about this "other stuff in `ConnectingRequest`" were just from looking at the code in `startHandshake` for things it pulled from the Factory right now. I'm not 100% sure what "resource" is, but it was `self.factory.resource` before now. I *think* it's just referring to the path-part of the URI, yes.

**Comment by meejah** [comment] 2019-04-03 21:38
My suggestion for the "parameter" aspect is this:

- nothing; you can access `self.transport` yourself (and access anything your framework has)
- be explicit: we pass "some object" that includes documented attributes (this object could just be `self.transport`, documenting "any attributes that exist in both Twisted and asyncio" or it could be a `TransportDetails` or similar object as oberstet outlined above)

A sort of "hybrid" approach would be to include a parameter, but "for now at least" it's just "your framework's transport". So that would be identical to "just access `self.transport`" except that at least the API includes this as a parameter and we could do something more like the second thing if/when that was needed.

**Comment by oberstet** [comment] 2019-04-06 12:05
thinking about, and relooking at the options discussed, I think I would opt for 2 new types `TransportDetails` and a `ConnectingRequest`, and go with

```python
class autobahn.websocket.protocol.WebSocketClientProtocol(autobahn.websocket.protocol.WebSocketProtocol):
    def onConnecting(self, transport_details: TransportDetails):
        return autobahn.websocket.types.ConnectingRequest(headers={'foo': 'bar'})
```

This allows user code to be written fully network-framework agnostic (at the source level) and provides non-breaking extensibility for the future (via the 2 types).

**Comment by meejah** [comment] 2019-04-09 22:08
Should `onConnecting` handle async / future-returning overrides? (If so, it would need to delay starting the handshake until any future resolved). For consistency, I think it probably should (i.e. in Python3 then everything can be `async def on*()` for all the various "user callbacks").

**Comment by oberstet** [comment] 2019-04-13 08:12
quick comments:

* making `onConnecting` async: that is cool
* making `onMessage` async: I would be -1 on that without extensive thinking, analysis and performance testing

**Comment by meejah** [comment] 2019-04-15 17:30
Yeah, okay good point about `onMessage`. I think it *does* make sense for `onConnecting` though (e.g., you might want to look up something in a database to put "something" in the headers)

**Comment by exarkun** [comment] 2019-04-15 17:33
> making onMessage async: I would be -1 on that without extensive thinking, analysis and performance testing. in fact, it might be wrong, as awaiting onMessage would effectively serialize all WebSocket message processing (at the WebSocket level) which is wrong

One reason you might _want_ this ability is as a way to provide back-pressure on the connection and avoid blowing up memory usage if your processing can't keep up with the messages arriving.

I have no idea if awaiting onMessage is the right way to provide this feature but it's a pretty nice feature and there is some appeal to having the simplest, most obvious way to structure your application code _automatically_ give you the feature.

**Comment by meejah** [comment] 2019-04-15 17:35
That would be a neat way to make backpressure work, yeah. I just mean that oberstet's point is good: we'd want to profile if well first to make sure that doing that doesn't slow down "most code which is using onMessage synchronously"

**Comment by oberstet** [comment] 2019-04-16 05:44
Ok, here are my 2cts;)

> I have no idea if awaiting onMessage is the right way

I agree on the _goal_ of having the ability to exert backpressure from the app via the library into Twisted and ultimately the kernel and the wire. But I don't think "it is the right way" to do as suggested.

"awaiting onMessage": `onMessage` is called by the library (autobahn), and hence I assume that the awaiting here refers to awaiting in the library.

Though making `onMessage` async and awaiting it in the library would "solve" the backpressure thing, it is not the right way, as it would simply serialize everything. It would _break_ 99% of apps, and it would also not "solve" backpressure thing sub-WebSocket message .. no control for receiving a single 10GB WebSocket message .. please see below.

A better way of backpressure control would not reach the goal by serializing everything, but exert backpressure when the total bytes / set of messages still being processed client side exceeds some value while letting the set-in-processing still run concurrently (not fully serialized).

In a way, it is roughly similar to databases: you _can_ make ACID happen by enforcing a single-writer and fully serialized system - but that comes with a big price;)

---

Having said that, here is an example of streaming WebSocket including backpressure:

* https://github.com/crossbario/autobahn-python/blob/master/examples/twisted/websocket/streaming/streaming_producer_client.py

This is using **Twisted producer/consumer system**

Note that this does not only solve backpressure on a per-WebSocket message level, but _also_ on a per-WebSocket frame and even within-WebSocket-message level. This is possible as Autobahn provides not only a pre-message, but also a pre-frame and per-bytes API for WebSocket.

Rgd the last: this provides backpressure handling even within a single huge WebSocket message. Consider what happens if you receive a WebSocket message of 10GB payload. Making `onMessage` async and awaiting it in the library wouldn't help at all .. it would not reach the goal and by serializing everything, break apps.

---

I am not claiming that above is a complete or perfect solution .. and yeah, I know about Twisted Tubes;) https://github.com/twisted/tubes

We could discuss the backpressure thing, but it is a much broader and deeper running topic than this present, relatively harmless issue. Eg a real solution might not involve Twisted.

Personally, I would consider (spend time) opening this can only within an even bigger scope: come up with a _next-gen network framework_ based on `io_submit`(https://blog.cloudflare.com/io_submit-the-epoll-alternative-youve-never-heard-about/) _and_ zero copy (as much as possible) eg https://github.com/alex/zero_buffer

**Comment by oberstet** [comment] 2019-04-22 10:40
this has landed on master  - though it is currently deactivated (https://github.com/crossbario/autobahn-python/pull/1183/commits/d8dc54472640ddf669b2d1956d582495dc61ba13) until we resolve https://github.com/crossbario/autobahn-python/issues/1181 (_and_ demonstrate it doesn't break crossbar/crossbarfx again;)

**Closed by oberstet** 2019-04-22 10:40 UTC
Labels: enhancement, needs-discussion, websocket
