### ISSUE TITLE
`tuple index out of range` if raising ApplicationError without args

### ISSUE THREAD

**Issue by schoonc** [crossbario/autobahn-python#528] opened 2015-10-16 22:11 UTC
Simplest example:
```
from autobahn.twisted.wamp import ApplicationSession
from autobahn.wamp import ApplicationError
from twisted.internet.defer import inlineCallbacks


class App(ApplicationSession):
    def test(self):
        raise ApplicationError(u'error')

    @inlineCallbacks
    def onJoin(self, details):
        yield self.register(self.test, u'test')
        yield self.call(u'test')
```
`tuple index out of range` appears in line `errmsg = u"{0}".format(err.value.args[0])` (file autobahn/wamp/protocol.py)

**Comment by jvdm** [comment] 2015-10-17 00:06
Duplicate of #484

**Closed** 2015-12-04 12:06 UTC
