### ISSUE TITLE
encrypt KeyRing in cryptobox AttributeError

### ISSUE THREAD

**Issue by jflorimo** [crossbario/autobahn-python#736] opened 2016-09-09 15:38 UTC
file cryptobox.py line 204 in the encrypt function:

line 204:
`payload_encr = box.encrypt(payload_ser, nonce, encoder=Base64Encoder)`

the box.encrypt() function returns an EncryptedMessage wich is a byte type, but a byte doesnt have an encrypt function

line 205:
`payload_bytes = payload_encr.encode().decode('ascii')`

this line raise "builtins.AttributeError: 'EncryptedMessage' object has no attribute 'encode'"

@BenjaminRepingon managed to fix this issues (with  #735 )by overriding the encrypt function.
with PyNaCl version is at 1.0.1 and authoban version set at 0.16.0

```
class CustomKeyRing(KeyRing):
    def encrypt(self, is_originator, uri, args=None, kwargs=None):
        """
        Encrypt the given WAMP URI, args and kwargs into an EncryptedPayload instance, or None
        if the URI should not be encrypted.
        """
        assert(type(uri) == six.text_type)
        assert(type(is_originator) == bool)
        assert(args is None or type(args) in (list, tuple))
        assert(kwargs is None or type(kwargs) == dict)

        box = self._get_box(is_originator, uri)

        if not box:
            return

        payload = {
            u'uri': uri,
            u'args': args,
            u'kwargs': kwargs
        }
        nonce = random(Box.NONCE_SIZE)

        # dumps return `str` and `box.encrypt` need `bytes`
        payload_ser = json.dumps(payload).encode()

        # box.encrypt return `bytes` (`EncryptedMessage`)
        payload_encr = box.encrypt(payload_ser, nonce, encoder=Base64Encoder)

        if isinstance(payload_encr, bytes):
            # decode directly work, if no decode('ascii') cause an AssertionError
            payload_bytes = payload_encr.decode('ascii')
        else:
            # and this raise "builtins.AttributeError: 'EncryptedMessage' object has no attribute 'encode'"
            payload_bytes = payload_encr.encode().decode('ascii')
        payload_key = None

        return EncryptedPayload(u'cryptobox', payload_key, u'json', payload_bytes)
```

**Comment by oberstet** [comment] 2022-04-09 09:23
duplicate of https://github.com/crossbario/autobahn-python/issues/735

**Closed by oberstet** 2022-04-09 09:23 UTC
Labels: bug, Python 3
